/* O "*" SIGNIFICA QUE ESTOU PEGANDO TODOS OS NAMED EXPORTS QUE EU TENHO NO ARQUIVO DA ACTION, E ESTOU EXPORTANDO DAQUI MESMO, DAI VOU PODER FAZER UM DESTRUCT NA HORA DE IMPORTAR, POR EX.:
import { USER_LOGIN, USER_LOGOUT } from "../action";
*/
export * from "./userActions";